services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=bekzod123
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5437:5432'
    networks:
      - postgres
    restart: unless-stopped

  redis:
    image: redis
    ports:
      - '6375:6379'

networks:
  postgres:
    driver: bridge
