version: '1.0'

services:
  server:
    build:
      context: .
    container_name: Auth
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:16-alpine
    container_name: nestjs_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5434:5432'